additionalProperties:
  npmName: "openai"
  npmVersion: "3.3.0"
  supportsES6: true
  withNodeImports: false
files:
  tsc-multi.mustache:
    templateType: SupportingFiles
    destinationFilename: tsc-multi.json
  stream.mustache:
    templateType: SupportingFiles
    destinationFilename: stream.ts